<a href="https://colab.research.google.com/github/joselyn-li/datasci_1_loading/blob/main/coding_exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The following code cell below imports pandas**

We need pandas because we cannot load our datasets without it.

In [ ]:
import pandas as pd

In [ ]:
df1_path = '/content/Data/online food delivery dataset.csv'
read_df1 = pd.read_csv(df1_path)
read_df1 = read_df1.drop(columns=['Unnamed: 13'], errors='ignore')
read_df1.head(11)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive
5,27,Female,Married,Employee,More than 50000,Post Graduate,2,Regular,12.9299,77.6848,560103,Yes,Positive
6,22,Male,Single,Student,No Income,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive
7,24,Female,Single,Student,No Income,Post Graduate,3,Regular,12.9828,77.6131,560042,Yes,Positive
8,23,Female,Single,Student,No Income,Post Graduate,2,Regular,12.9766,77.5993,560001,Yes,Positive
9,23,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9854,77.7081,560048,Yes,Positive
10,22,Female,Single,Student,No Income,Post Graduate,5,Frequent,12.9850,77.5533,560010,Yes,Positive

**csv_data1 represents the following:**

General information about customers and their online food ordering behavior, data extracted 2026.

**Columns**

**1. Age**
* lists the customer's age in years (between 18 to 33), used to analyze the relationship between demographic cohorts and online food ordering behavior

**2. Gender**
* contains the self-reported gender identity of the customer to explore demogaphic-specific variations in meal preferences

**3. Marital Status**
* contains the legal relationship status of the customer to differeniate single-person habits from family ordering patterns

**4. Occupation**
* categorizes the customer as a student, employee, or other to evalute behavioral patterns across different occupational groups

**5. Monthly Income**
* contains the income bracket of the customer to analyze correlation between income-related factors and ordering habits

**6. Educational Qualifications**
* categorizes the customer's highest level of education as graduate, post-graduate, or other, to assist in customer segmentation

**7. Family Size**
* lists the total number of individuals in the household to investigate the relationship between family-related factors and food ordering trends

**8. Customer Type**
* categorizes the customer as regular, frequent, or other to understand engagement patterns

**9 and 10. Latitude / Longitude**
* lists the exact geospatial coordinates of the customer to visualize and analyze location-related factors influencing food delivery

**11. Pin Code**
* lists the regional postal code of the delivery address to enable geographic customer segmentation and regional pattern analysis

**12. Feedback**
* categorizes the customer's feedback as positive or negative to understand platform satisfaction levels

In [ ]:
df2_path = '/content/Data/index_1.csv'
read_df2 = pd.read_csv(df2_path)
read_df2.head(11)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,Americano with Milk
10,2024-03-01,2024-03-01 19:29:17.391,card,ANON-0000-0000-0009,33.8,Americano with Milk

**csv_data2 represents the following:**

Detailed records of coffee sales from a vending machine in March 2024.

**Columns**

**1. Date**
* contains the calendar date of purchase to monitor daily sales trend over time

**2. Datetime**
* details the exact timestamp of the transaction to track continious daily volumes

**3. Cash Type**
* categorizes the transcation as either cash or card to evaluate transaction method trends

**4. Card**
* records an anonymized card identifer to track repeat buyers and individual purchasing frequencies

**5. Money**
* measures the amount paid for the beverage in local currency to evaluate revenue

**6. Coffee Name**
* specifies the exact beverage option selected
(Example: Latte, Americano, Hot Chocolate) to gauge product-level popularity

In [ ]:
df3_path = '/content/Data/Data_Train.xlsx'
read_df3 = pd.read_excel(df3_path)
read_df3.head(11)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
6,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087
7,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270
8,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625
10,Air India,1/06/2019,Delhi,Cochin,DEL → BLR → COK,09:45,23:00,13h 15m,1 stop,No info,8907

**xlsx_data1 represents the following:**

A comprehensive collection of flight booking records from the EaseMyTrip platform in 2019.

**Columns**

**1. Airline**
* lists the name of the operating airline company to evalute brand-specific pricing strategies

**2. Date of Journey**
* records the calendar date of the scheduled flight departure to analyze price variations

**3. Source**
* lists the departure airport location

**4. Destination**
* lists the landing airport location

**5. Route**
* records the specific sequence of airways and intermediate transit stops between the source and destination cities to account for pathway-specific pricing variances

**6 and 7. Departure Time / Arrival Time**
* details the specfic departure and arrival time to evaluate how specific time-of-day pairings influence passenger ticket pricing

**8. Duration**
* calculates the total travel time between cities in hours

**9. Total Stops**
* quantifies the exact number of layovers a flight makes between the source and destination cities to evaluate how multi-stop discounted ticket prices compare to direct routes

**10. Additional Info**
* records any extra accomodations included with the ticket purchase (Example: airline meal inclusions) to evaluate how added amenities or travel restrictions affect the final ticket price

**11. Price**
* measures the final cost of the plane ticket

In [ ]:
df4_path = '/content/Data/Flipkart-Laptops.xlsx'
read_df4 = pd.read_excel(df4_path)
read_df4.head(11)

,Product Name,ProductID,Product image,Actual price,Discount price,Stars,Rating,Reviews,Description,Link
0,MSI Cyborg 15 Intel Core i5 12th Gen 12450H - ...,COMGZW35W3DSJADN,NaN,89990,54990,3.9,7 Ratings,1 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR5 R...,https://www.flipkart.com/msi-cyborg-15-intel-c...
1,MSI Thin 15 Intel Core i7 12th Gen 12650H - (8...,COMGZW37ZX66DBHF,NaN,83990,67990,NIL,NIL,NIL,Intel Core i7 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/msi-thin-15-intel-cor...
2,DELL Inspiron 3520 Intel Core i3 12th Gen 1215...,COMGJ75HJGFDJ6JN,NaN,49240,35660,4.2,"1,805 Ratings",143 Reviews,Intel Core i3 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/dell-inspiron-3520-in...
3,Acer One (2024) Intel Core i3 11th Gen 1115G4 ...,COMGPF5CQ7VDWDT4,NaN,43999,26990,4.2,"6,977 Ratings",596 Reviews,Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,https://www.flipkart.com/acer-one-2024-intel-c...
4,Lenovo V15 AMD Ryzen 3 Quad Core 7320U - (8 GB...,COMGPYKZAWY8UX6C,NaN,59400,27989,4.2,"1,263 Ratings",113 Reviews,AMD Ryzen 3 Quad Core Processor8 GB LPDDR5 RAM...,https://www.flipkart.com/lenovo-v15-amd-ryzen-...
5,Lenovo AMD Ryzen 3 Quad Core 7330U - (8 GB/512...,COMGYG23H3CRABUT,NaN,63900,32990,5,7 Ratings,0 Reviews,AMD Ryzen 3 Quad Core Processor8 GB DDR4 RAMWi...,https://www.flipkart.com/lenovo-amd-ryzen-3-qu...
6,HP FQ Series Intel Core i3 12th Gen 1215U - (8...,COMHFG63BRFVGXHW,NaN,50843,36175,4.6,5 Ratings,0 Reviews,Intel Core i3 Processor (12th Gen)8 GB DDR4 RA...,https://www.flipkart.com/hp-fq-series-intel-co...
7,HP ENVY AMD Ryzen 5 Hexa Core 8640HS - (16 GB/...,COMGYFMD3GYK34ZS,NaN,99148,84490,2.3,3 Ratings,0 Reviews,AMD Ryzen 5 Hexa Core Processor16 GB LPDDR5 RA...,https://www.flipkart.com/hp-envy-amd-ryzen-5-h...
8,Acer Swift Go 14 EVO OLED Intel Core i5 13th G...,COMGZKGGAHZBA3WY,NaN,93999,59990,4.3,"1,098 Ratings",108 Reviews,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...,https://www.flipkart.com/acer-swift-go-14-evo-...
9,HP Laptop AMD Ryzen 3 Quad Core 5300U - (8 GB/...,COMGHAGN3U9FJH39,NaN,44783,35490,4.3,"4,029 Ratings",466 Reviews,AMD Ryzen 3 Quad Core Processor8 GB DDR4 RAMWi...,https://www.flipkart.com/hp-laptop-amd-ryzen-3...
10,ASUS TUF Gaming A15 (2024) AMD Ryzen 7 Octa Co...,COMGZW3FGTJMSNNM,NaN,143990,124990,NIL,NIL,NIL,AMD Ryzen 7 Octa Core Processor16 GB DDR5 RAMW...,https://www.flipkart.com/asus-tuf-gaming-a15-2...

**xlsx_data2 represents the following:**

A comprehensive overview of available laptops on an e-commerce platform.

**Columns**

**1. Product Name**
* lists the official name of the laptop

**2. Product ID**
* lists the unique barcode or ID for each laptop to tell products apart when tracking stock or sales

**3. Product Image**
* intended to link to the product photo, but currently displays as NaN, indicating missing data

**4. Actual Price**
* shows the original retail cost of the product before any sales to track the baseline value of inventory

**5. Discount Price**
* shows the lowered price after markdowns to analyze price optimization algorithms and buying trends

**6. Stars**
* displays the review score

**7. Rating**
* displays the actual mathematical average score given by shoppers to help rank products from highest to lowest quality

**8. Reviews**
* tracks the total number of customer feedback submissions left for the product to evaluate how popular and heavily discussed an item is across the platform

**9. Description**
* contains the written overview of the item's features and specifications

**10. Link**
* directs users straight to the live e-commerce page to check out details of a specfic laptop

In [ ]:
df5_path = '/content/Data/Online Retail.xlsx'
read_df5 = pd.read_excel(df5_path)
read_df5.head(11)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom

**xlsx_data3 represents the following:**

General information of transactions that occurred for a UK-based and registered, online retail store in 2010.

**Columns**

**1. Invoice Number**
* lists a unique 6-digit receipt number for each order

**2. Stock Code**
* lists a unique 5-digit barcode assigned to each specific gift item to track inventory and product-level sales

**3. Description**
* contains a written overview of the item's features

**4. Quantity**
* measures the number of items purchased per transaction

**5. Invoice Date**
* details the exact timestamp of the transaction

**6. Unit Price**
* lists the price per individual item in British Pounds to calculate total revenue per invoice

**7. CustomerID**
* lists a unique 5-digit shopper ID number to identify repeat wholesale buyers

**8. Country**
* lists the geographic market location to track domestic vs international transactions

In [ ]:
import json
df6_path = '/content/Data/holidays-us.json'
with open(df6_path, 'r') as f:
    json_data = json.load(f)
read_json1 = pd.json_normalize(json_data, record_path=['holidays'])
read_json1.head(11)

,name,date,type,observed,paid
0,New Year's Day,January 1,Federal,True,True
1,Martin Luther King Jr. Day,Third Monday of January,Federal,True,True
2,Presidents' Day,Third Monday of February,Federal,True,True
3,Memorial Day,Last Monday of May,Federal,True,True
4,Juneteenth,June 19,Federal,True,True
5,Independence Day,July 4,Federal,True,True
6,Labor Day,First Monday of September,Federal,True,True
7,Columbus Day,Second Monday of October,Federal,True,True
8,Veterans Day,November 11,Federal,True,True
9,Thanksgiving Day,Fourth Thursday of November,Federal,True,True
10,Christmas Day,December 25,Federal,True,True

**json_data1 represents the following:**

General information about US holidays

**Columns**

**1. Name**
* lists the name of the holiday

**2. Date**
* represents the calendar placement or scheduling logic of the holiday to establish when the holiday occurs annually

**3. Type**
* categorizes the holiday by its official legal or cultural category to differentiate legal government shutdowns (Federal), widespread cultural observances (Cultural), or faith-based calendar dates (Religious)

**4. Observed**
* categorizes the holiday as an observed federal/corporate day off (Yes) or the actual, traditional calendar date of the holiday (No) to identify when public closures, bank holidays, and payroll shifts occur if a fixed-date holiday happens to fall on a Saturday or Sunday

**5. Paid**
* identifies whether the holiday is a paid day off for employees (True) or an unpaid/cultural event (False) to distinguish official, corporate paid holidays from other widely celebrated calendar events (like Halloween or Valentine's Day)

In [ ]:
import json
df7_path = '/content/Data/colors.json'
with open(df7_path, 'r') as f:
    json_data = json.load(f)
read_json1 = pd.json_normalize(json_data, record_path=['colors'])
read_json1.head(11)

       name      hex   category  rgb.r  rgb.g  rgb.b
0     Black  #000000    neutral      0      0      0
1     White  #FFFFFF    neutral    255    255    255
2       Red  #FF0000    primary    255      0      0
3     Green  #00FF00    primary      0    255      0
4      Blue  #0000FF    primary      0      0    255
5    Yellow  #FFFF00  secondary    255    255      0
6      Cyan  #00FFFF  secondary      0    255    255
7   Magenta  #FF00FF  secondary    255      0    255
8    Orange  #FFA500       warm    255    165      0
9      Pink  #FFC0CB       warm    255    192    203
10   Purple  #800080       cool    128      0    128

**json_data2 represents the following:**

A structured catalog of digital colors designed for color theory analysis and UI design applications.

**Columns**

**1. Name**
* lists the name of different colors

**2. Hex**
* lists the exact hexadecimal value that provides a standardized, universally recognized code for computer systems, web browsers, and design softwares to accurately render the specific color on a screen

**3. Category**
* classifies the color based on its color theory placement or temperature profile to allow designers or applications to easily group, filter, and query colors by their functional role in a palette

**4, 5 and 6. Rgb.r/ Rgb.g / Rgb.b**
* classifies the individual intensities of the red, green, and blue channels that make up the RGB color model. The primary purpose of these three combined features is to break down the color into its fundamental light components, allowing digital screens and graphics software to blend them together to reproduce the exact color.

In [44]:
df8 = '/content/Data/iris_data.json'
read_json1 = pd.read_json(df8)
read_json1.head(11)

    sepal length  sepal width  petal length  petal width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa

**json_data3 represents the following:**

The physical measurements of different iris flowers among three different species

**Columns**

**1. Sepal Length**
* the length of flower's sepal measured in cm, to describe the size of the outer part of the flower

**2. Sepal Width**
* the width of flower's sepal measured in cm, to indicate how wide the outer part of the flower is

**3. Petal Length**
* the length of the flower's petal measured in cm, to describe the size of the petal

**4. Petal Width**
* the width of the flower's petal measured in cm, to indicate how wide the petal is

**5. Species**
* identifies the species of the iris flower